### OOPS Concepts

#### Inheritance

Single Inheritance

In [20]:
class Father:
    def __init__(self, name, age):
        self.name = name
        self.age = age

    def do_math(self):
        print(self.name, " is good at math")

class Son(Father):
    def __init__(self, name, age):
        super().__init__(name, age)

    def do_physics(self):
        print(self.name, " is good at physics")

son1 = Son("karthikeya", 24)
father1 = Son("akash", 30)
son1.do_math()
son1.do_physics()

karthikeya  is good at math
karthikeya  is good at physics

Hierarchical Inheritance

In [21]:
class Father:
    def __init__(self, name, age):
        self.name = name
        self.age = age

    def do_math(self):
        print(self.name, " is good at math")

class Son(Father):
    def __init__(self, name, age):
        super().__init__(name, age)

    def do_physics(self):
        print(self.name, " is good at physics")

class Daughter(Father):
    def __init__(self, name, age):
        super().__init__(name, age)

    def do_chemistry(self):
        print(self.name, " is good at chemistry")

son1 = Son("karthikeya", 24)
daughter1 = Daughter("manjunatha", 20)
daughter1.do_math()
daughter1.do_chemistry()

manjunatha  is good at math
manjunatha  is good at chemistry

Multilevel Inheritance

In [22]:
class Father:
    def __init__(self, name, age):
        self.name = name
        self.age = age

    def do_math(self):
        print(self.name, " is good at math")

class Son(Father):
    def __init__(self, name, age):
        super().__init__(name, age)

    def do_physics(self):
        print(self.name, " is good at physics")

class Grandson(Son):
    def __init__(self, name, age):
        super().__init__(name, age)

    def do_computer_science(self):
        print(self.name, "is good at computer science")

son1 = Son("karthikeya", 24)
grandson = Grandson("venkatesh", 26)
grandson.do_computer_science()
grandson.do_math()
grandson.do_physics()

venkatesh is good at computer science
venkatesh  is good at math
venkatesh  is good at physics

Multiple Inheritance

In [23]:
class Father:
    def __init__(self, name, age):
        self.name = name
        self.age = age

    def do_math(self):
        print(self.name, " is good at calculus")

class Mother:
    def __init__(self, name, age):
        self.name = name
        self.age = age

    def do_law(self):
        print(self.name, "is good at law")

    def do_math(self):
        print(self.name, "is good at vector")

class Son(Father, Mother):
    def __init__(self, name, age):
        super().__init__(name, age)

    def do_physics(self):
        print(self.name, " is good at physics")

son1 = Son("krishna", 26)
son1.do_math()

krishna  is good at calculus

#### Polymorphism

Method Overloading (Not supported in Python like Java)

In [24]:
class A:
    def do_math(self, minutes, hours):
        print(f"First think and then solve the problem for {minutes} mins")
    
    def do_math(self, minutes, hours=30):
        print(f"First think for {minutes} mins and then solve for {hours} hours")

obj = A()
obj.do_math(20)

First think for 20 mins and then solve for 30 hours

Method Overriding

In [25]:
class A:
    def do_math(self, minutes):
        print(f"First think and then solve the problem for {minutes} mins")

class B(A):
    def do_math(self, minutes, hours):
        print(f"First think and then solve the problem for {minutes} mins and {hours} hours")

obj = A()
obj.do_math(20)

obj = B()
obj.do_math(20, 30)

First think and then solve the problem for 20 mins
First think and then solve the problem for 20 mins and 30 hours

#### Abstraction (with ABS: Abstract Base Class)

Contract Creation like Interfaces in Java

In [26]:
from abc import ABC, abstractmethod

class BikeRule(ABC):
    @abstractmethod
    def apply_brake(self):
        pass
    
    # If Method Overriden then abstract method is no longer abstract, we can create object and call
    # def apply_brake(self):
    #     print("applying brake mechanism")

class Honda(BikeRule):
    # Compulsory to implement this method
    def apply_brake(self):
        print("Honda's brake mechanism")

    def start_engine(self):
        print("Engine starting mechanism")

obj = Honda()
obj.start_engine()
obj.apply_brake()

Engine starting mechanism
Honda's brake mechanism

#### Encapsulation

In [27]:
class Account:
    def __init__(self, name, account_number):
        self._name = name
        self.__account_number = account_number
    
    def get_name(self):
        return self._name
    
    def get_account_number(self):
        return self.__account_number

sbi_one = Account("akash", "3328")
print(sbi_one.get_name())
print(sbi_one.get_account_number())

# Hack to access private variable (protected can also be accessed by prefixing with underscore)
# print(sbi_one._Account__account_number)

# To see all methods that can be called from a class
# dir(object)

akash
3328

#### Magic Methods (Also known as dunder methods i.e double underscore methods)

In [28]:
class Student:
    def __init__(self, name, age):
        self.name = name
        self.age = age
    
    def __str__(self):
        return f'Name is {self.name} and age is {self.age}'

student1 = Student("akash", 24)
print(student1)

Name is akash and age is 24

#### Operator Overloading

In [29]:
class Vector:
    def __init__(self, first, second):
        self.first = first
        self.second = second
    
    # Overloading the PLUS operator (We can overload many operators but it should have dunder method available)
    def __add__(self, other):
        return Vector(self.first + other.first, self.second + other.second)
    
    def __str__(self):
        return f'({self.first}, {self.second})'

v1 = Vector(4, 6)
v2 = Vector(6, 9)
v3 = v1 + v2
print(v3)

(10, 15)

#### Iterators

In [30]:
s = "akash is a good boy but according to whose definition of good"
it = iter(s)
while True:
    try:
        x = next(it)
        print(x, end = "")
    except:
        print("\nAll elements are printed")
        break

akash is a good boy but according to whose definition of good
All elements are printed

#### Generators

In [31]:
def square(n):
    for i in range(n):
        yield(i*i)

for i in square(10):
    print(i, end = " ")

0 1 4 9 16 25 36 49 64 81

#### Decorators

In [32]:
def my_decorator(func):

    def wrapper():
        print("Before function")
        func()
        print("After function")

    return wrapper

@my_decorator
def do_math():
    print("I am solving some maths problem")

do_math()

Before function
I am solving some maths problem
After function

#### Series

In [33]:
data = {
    0: "Akash",
    1: "Vijay",
    2: "Ganesh"
}

In [4]:
import pandas as pd
series = pd.Series(data)
series

Name         [Akash, Vijay, Vasanth]
Age                     [25, 29, 31]
Hobby    [Cricket, Singing, Dancing]
dtype: object

In [5]:
series[2] = "Kanhaiya"
series

Name         [Akash, Vijay, Vasanth]
Age                     [25, 29, 31]
Hobby    [Cricket, Singing, Dancing]
2                           Kanhaiya
dtype: object

In [6]:
data = {
    "Name": ["Akash", "Vijay", "Vasanth"],
    "Age": [25, 29, 31],
    "Hobby": ["Cricket", "Singing", "Dancing"]
}

df = pd.DataFrame(data)
print(df)

      Name  Age    Hobby
0    Akash   25  Cricket
1    Vijay   29  Singing
2  Vasanth   31  Dancing

In [7]:
df['Name']

0      Akash
1      Vijay
2    Vasanth
Name: Name, dtype: str

In [8]:
df.loc[0]

Name       Akash
Age           25
Hobby    Cricket
Name: 0, dtype: object

In [9]:
df

      Name  Age    Hobby
0    Akash   25  Cricket
1    Vijay   29  Singing
2  Vasanth   31  Dancing

In [10]:
df['Language']=['Kannada', 'Kannada', 'Tamil']
df

      Name  Age    Hobby Language
0    Akash   25  Cricket  Kannada
1    Vijay   29  Singing  Kannada
2  Vasanth   31  Dancing    Tamil

In [11]:
df

      Name  Age    Hobby Language
0    Akash   25  Cricket  Kannada
1    Vijay   29  Singing  Kannada
2  Vasanth   31  Dancing    Tamil

In [12]:
df.drop(1)

      Name  Age    Hobby Language
0    Akash   25  Cricket  Kannada
2  Vasanth   31  Dancing    Tamil

In [15]:
df.loc[1] = ["Vijay", 30, "Singing", "Kannada"]

In [16]:
df

      Name  Age    Hobby Language
0    Akash   25  Cricket  Kannada
1    Vijay   30  Singing  Kannada
2  Vasanth   31  Dancing    Tamil

In [21]:
df.at[1, 'Language']

'Kannada'

In [23]:
df

      Name  Age    Hobby Language
0    Akash   25  Cricket  Kannada
1    Vijay   30  Singing  Kannada
2  Vasanth   31  Dancing    Tamil

In [27]:
df.iat[1,0]

'Vijay'

In [28]:
df['Age']=df['Age']+1

In [29]:
df

      Name  Age    Hobby Language
0    Akash   26  Cricket  Kannada
1    Vijay   31  Singing  Kannada
2  Vasanth   32  Dancing    Tamil

In [30]:
df.describe()

             Age
count   3.000000
mean   29.666667
std     3.214550
min    26.000000
25%    28.500000
50%    31.000000
75%    31.500000
max    32.000000

In [2]:
import pandas as pd

df = pd.read_csv("data.csv")
df

          Date Category  Value   Product  Sales Region
0   2023-01-01        A   28.0  Product1  754.0   East
1   2023-01-02        B   39.0  Product3  110.0  North
2   2023-01-03        C   32.0  Product2  398.0   East
3   2023-01-04        B    8.0  Product1  522.0   East
4   2023-01-05        B   26.0  Product3  869.0  North
5   2023-01-06        B   54.0  Product3  192.0   West
6   2023-01-07        A   16.0  Product1  936.0   East
7   2023-01-08        C   89.0  Product1  488.0   West
8   2023-01-09        C   37.0  Product3  772.0   West
9   2023-01-10        A   22.0  Product2  834.0   West
10  2023-01-11        B    7.0  Product1  842.0  North
11  2023-01-12        B   60.0  Product2    NaN   West
12  2023-01-13        A   70.0  Product3  628.0  South
13  2023-01-14        A   69.0  Product1  423.0   East
14  2023-01-15        A   47.0  Product2  893.0   West
15  2023-01-16        C    NaN  Product1  895.0  North
16  2023-01-17        C   93.0  Product2  511.0  South
17  2023-01-18        C    NaN  Product1  108.0   West
18  2023-01-19        A   31.0  Product2  578.0   West
19  2023-01-20        A   59.0  Product1  736.0   East
20  2023-01-21        C   82.0  Product3  606.0  South
21  2023-01-22        C   37.0  Product2  992.0  South
22  2023-01-23        B   62.0  Product3  942.0  North
23  2023-01-24        C   92.0  Product2  342.0   West
24  2023-01-25        A   24.0  Product2  458.0   East
25  2023-01-26        C   95.0  Product1  584.0   West
26  2023-01-27        C   71.0  Product2  619.0  North
27  2023-01-28        C   56.0  Product2  224.0  North
28  2023-01-29        B    NaN  Product3  617.0  North
29  2023-01-30        C   51.0  Product2  737.0  South
30  2023-01-31        B   50.0  Product3  735.0   West
31  2023-02-01        A   17.0  Product2  189.0   West
32  2023-02-02        B   63.0  Product3  338.0  South
33  2023-02-03        C   27.0  Product3    NaN   East
34  2023-02-04        C   70.0  Product3  669.0   West
35  2023-02-05        B   60.0  Product2    NaN   West
36  2023-02-06        C   36.0  Product3  177.0   East
37  2023-02-07        C    2.0  Product1    NaN  North
38  2023-02-08        C   94.0  Product1  408.0  South
39  2023-02-09        A   62.0  Product1  155.0   West
40  2023-02-10        B   15.0  Product1  578.0   East
41  2023-02-11        C   97.0  Product1  256.0   East
42  2023-02-12        A   93.0  Product3  164.0   West
43  2023-02-13        A   43.0  Product3  949.0   East
44  2023-02-14        A   96.0  Product3  830.0   East
45  2023-02-15        B   99.0  Product2  599.0   West
46  2023-02-16        B    6.0  Product1  938.0  South
47  2023-02-17        B   69.0  Product3  143.0   West
48  2023-02-18        C   65.0  Product3  182.0  North
49  2023-02-19        C   11.0  Product3  708.0  North

In [3]:
df.isna()

     Date  Category  Value  Product  Sales  Region
0   False     False  False    False  False   False
1   False     False  False    False  False   False
2   False     False  False    False  False   False
3   False     False  False    False  False   False
4   False     False  False    False  False   False
5   False     False  False    False  False   False
6   False     False  False    False  False   False
7   False     False  False    False  False   False
8   False     False  False    False  False   False
9   False     False  False    False  False   False
10  False     False  False    False  False   False
11  False     False  False    False   True   False
12  False     False  False    False  False   False
13  False     False  False    False  False   False
14  False     False  False    False  False   False
15  False     False   True    False  False   False
16  False     False  False    False  False   False
17  False     False   True    False  False   False
18  False     False  False    False  False   False
19  False     False  False    False  False   False
20  False     False  False    False  False   False
21  False     False  False    False  False   False
22  False     False  False    False  False   False
23  False     False  False    False  False   False
24  False     False  False    False  False   False
25  False     False  False    False  False   False
26  False     False  False    False  False   False
27  False     False  False    False  False   False
28  False     False   True    False  False   False
29  False     False  False    False  False   False
30  False     False  False    False  False   False
31  False     False  False    False  False   False
32  False     False  False    False  False   False
33  False     False  False    False   True   False
34  False     False  False    False  False   False
35  False     False  False    False   True   False
36  False     False  False    False  False   False
37  False     False  False    False   True   False
38  False     False  False    False  False   False
39  False     False  False    False  False   False
40  False     False  False    False  False   False
41  False     False  False    False  False   False
42  False     False  False    False  False   False
43  False     False  False    False  False   False
44  False     False  False    False  False   False
45  False     False  False    False  False   False
46  False     False  False    False  False   False
47  False     False  False    False  False   False
48  False     False  False    False  False   False
49  False     False  False    False  False   False

In [4]:
df.isna().any(axis=1)

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11     True
12    False
13    False
14    False
15     True
16    False
17     True
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28     True
29    False
30    False
31    False
32    False
33     True
34    False
35     True
36    False
37     True
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
46    False
47    False
48    False
49    False
dtype: bool

In [5]:
df.isna().any(axis=0)

Date        False
Category    False
Value        True
Product     False
Sales        True
Region      False
dtype: bool

In [6]:
df.isna().sum()

Date        0
Category    0
Value       3
Product     0
Sales       4
Region      0
dtype: int64

In [7]:
df

          Date Category  Value   Product  Sales Region
0   2023-01-01        A   28.0  Product1  754.0   East
1   2023-01-02        B   39.0  Product3  110.0  North
2   2023-01-03        C   32.0  Product2  398.0   East
3   2023-01-04        B    8.0  Product1  522.0   East
4   2023-01-05        B   26.0  Product3  869.0  North
5   2023-01-06        B   54.0  Product3  192.0   West
6   2023-01-07        A   16.0  Product1  936.0   East
7   2023-01-08        C   89.0  Product1  488.0   West
8   2023-01-09        C   37.0  Product3  772.0   West
9   2023-01-10        A   22.0  Product2  834.0   West
10  2023-01-11        B    7.0  Product1  842.0  North
11  2023-01-12        B   60.0  Product2    NaN   West
12  2023-01-13        A   70.0  Product3  628.0  South
13  2023-01-14        A   69.0  Product1  423.0   East
14  2023-01-15        A   47.0  Product2  893.0   West
15  2023-01-16        C    NaN  Product1  895.0  North
16  2023-01-17        C   93.0  Product2  511.0  South
17  2023-01-18        C    NaN  Product1  108.0   West
18  2023-01-19        A   31.0  Product2  578.0   West
19  2023-01-20        A   59.0  Product1  736.0   East
20  2023-01-21        C   82.0  Product3  606.0  South
21  2023-01-22        C   37.0  Product2  992.0  South
22  2023-01-23        B   62.0  Product3  942.0  North
23  2023-01-24        C   92.0  Product2  342.0   West
24  2023-01-25        A   24.0  Product2  458.0   East
25  2023-01-26        C   95.0  Product1  584.0   West
26  2023-01-27        C   71.0  Product2  619.0  North
27  2023-01-28        C   56.0  Product2  224.0  North
28  2023-01-29        B    NaN  Product3  617.0  North
29  2023-01-30        C   51.0  Product2  737.0  South
30  2023-01-31        B   50.0  Product3  735.0   West
31  2023-02-01        A   17.0  Product2  189.0   West
32  2023-02-02        B   63.0  Product3  338.0  South
33  2023-02-03        C   27.0  Product3    NaN   East
34  2023-02-04        C   70.0  Product3  669.0   West
35  2023-02-05        B   60.0  Product2    NaN   West
36  2023-02-06        C   36.0  Product3  177.0   East
37  2023-02-07        C    2.0  Product1    NaN  North
38  2023-02-08        C   94.0  Product1  408.0  South
39  2023-02-09        A   62.0  Product1  155.0   West
40  2023-02-10        B   15.0  Product1  578.0   East
41  2023-02-11        C   97.0  Product1  256.0   East
42  2023-02-12        A   93.0  Product3  164.0   West
43  2023-02-13        A   43.0  Product3  949.0   East
44  2023-02-14        A   96.0  Product3  830.0   East
45  2023-02-15        B   99.0  Product2  599.0   West
46  2023-02-16        B    6.0  Product1  938.0  South
47  2023-02-17        B   69.0  Product3  143.0   West
48  2023-02-18        C   65.0  Product3  182.0  North
49  2023-02-19        C   11.0  Product3  708.0  North

In [10]:
df['Sales_filled_NA']=df['Sales'].fillna(df['Sales'].mean())
df

          Date Category  Value   Product  Sales Region  Sales_filled_NA
0   2023-01-01        A   28.0  Product1  754.0   East       754.000000
1   2023-01-02        B   39.0  Product3  110.0  North       110.000000
2   2023-01-03        C   32.0  Product2  398.0   East       398.000000
3   2023-01-04        B    8.0  Product1  522.0   East       522.000000
4   2023-01-05        B   26.0  Product3  869.0  North       869.000000
5   2023-01-06        B   54.0  Product3  192.0   West       192.000000
6   2023-01-07        A   16.0  Product1  936.0   East       936.000000
7   2023-01-08        C   89.0  Product1  488.0   West       488.000000
8   2023-01-09        C   37.0  Product3  772.0   West       772.000000
9   2023-01-10        A   22.0  Product2  834.0   West       834.000000
10  2023-01-11        B    7.0  Product1  842.0  North       842.000000
11  2023-01-12        B   60.0  Product2    NaN   West       557.130435
12  2023-01-13        A   70.0  Product3  628.0  South       628.000000
13  2023-01-14        A   69.0  Product1  423.0   East       423.000000
14  2023-01-15        A   47.0  Product2  893.0   West       893.000000
15  2023-01-16        C    NaN  Product1  895.0  North       895.000000
16  2023-01-17        C   93.0  Product2  511.0  South       511.000000
17  2023-01-18        C    NaN  Product1  108.0   West       108.000000
18  2023-01-19        A   31.0  Product2  578.0   West       578.000000
19  2023-01-20        A   59.0  Product1  736.0   East       736.000000
20  2023-01-21        C   82.0  Product3  606.0  South       606.000000
21  2023-01-22        C   37.0  Product2  992.0  South       992.000000
22  2023-01-23        B   62.0  Product3  942.0  North       942.000000
23  2023-01-24        C   92.0  Product2  342.0   West       342.000000
24  2023-01-25        A   24.0  Product2  458.0   East       458.000000
25  2023-01-26        C   95.0  Product1  584.0   West       584.000000
26  2023-01-27        C   71.0  Product2  619.0  North       619.000000
27  2023-01-28        C   56.0  Product2  224.0  North       224.000000
28  2023-01-29        B    NaN  Product3  617.0  North       617.000000
29  2023-01-30        C   51.0  Product2  737.0  South       737.000000
30  2023-01-31        B   50.0  Product3  735.0   West       735.000000
31  2023-02-01        A   17.0  Product2  189.0   West       189.000000
32  2023-02-02        B   63.0  Product3  338.0  South       338.000000
33  2023-02-03        C   27.0  Product3    NaN   East       557.130435
34  2023-02-04        C   70.0  Product3  669.0   West       669.000000
35  2023-02-05        B   60.0  Product2    NaN   West       557.130435
36  2023-02-06        C   36.0  Product3  177.0   East       177.000000
37  2023-02-07        C    2.0  Product1    NaN  North       557.130435
38  2023-02-08        C   94.0  Product1  408.0  South       408.000000
39  2023-02-09        A   62.0  Product1  155.0   West       155.000000
40  2023-02-10        B   15.0  Product1  578.0   East       578.000000
41  2023-02-11        C   97.0  Product1  256.0   East       256.000000
42  2023-02-12        A   93.0  Product3  164.0   West       164.000000
43  2023-02-13        A   43.0  Product3  949.0   East       949.000000
44  2023-02-14        A   96.0  Product3  830.0   East       830.000000
45  2023-02-15        B   99.0  Product2  599.0   West       599.000000
46  2023-02-16        B    6.0  Product1  938.0  South       938.000000
47  2023-02-17        B   69.0  Product3  143.0   West       143.000000
48  2023-02-18        C   65.0  Product3  182.0  North       182.000000
49  2023-02-19        C   11.0  Product3  708.0  North       708.000000

In [11]:
df.head()

         Date Category  Value   Product  Sales Region  Sales_filled_NA
0  2023-01-01        A   28.0  Product1  754.0   East            754.0
1  2023-01-02        B   39.0  Product3  110.0  North            110.0
2  2023-01-03        C   32.0  Product2  398.0   East            398.0
3  2023-01-04        B    8.0  Product1  522.0   East            522.0
4  2023-01-05        B   26.0  Product3  869.0  North            869.0

In [16]:
df=df.rename(columns={'Date':'date', 'Category':'category'})
df

          date category  Value   Product  Sales Region  Sales_filled_NA
0   2023-01-01        A   28.0  Product1  754.0   East       754.000000
1   2023-01-02        B   39.0  Product3  110.0  North       110.000000
2   2023-01-03        C   32.0  Product2  398.0   East       398.000000
3   2023-01-04        B    8.0  Product1  522.0   East       522.000000
4   2023-01-05        B   26.0  Product3  869.0  North       869.000000
5   2023-01-06        B   54.0  Product3  192.0   West       192.000000
6   2023-01-07        A   16.0  Product1  936.0   East       936.000000
7   2023-01-08        C   89.0  Product1  488.0   West       488.000000
8   2023-01-09        C   37.0  Product3  772.0   West       772.000000
9   2023-01-10        A   22.0  Product2  834.0   West       834.000000
10  2023-01-11        B    7.0  Product1  842.0  North       842.000000
11  2023-01-12        B   60.0  Product2    NaN   West       557.130435
12  2023-01-13        A   70.0  Product3  628.0  South       628.000000
13  2023-01-14        A   69.0  Product1  423.0   East       423.000000
14  2023-01-15        A   47.0  Product2  893.0   West       893.000000
15  2023-01-16        C    NaN  Product1  895.0  North       895.000000
16  2023-01-17        C   93.0  Product2  511.0  South       511.000000
17  2023-01-18        C    NaN  Product1  108.0   West       108.000000
18  2023-01-19        A   31.0  Product2  578.0   West       578.000000
19  2023-01-20        A   59.0  Product1  736.0   East       736.000000
20  2023-01-21        C   82.0  Product3  606.0  South       606.000000
21  2023-01-22        C   37.0  Product2  992.0  South       992.000000
22  2023-01-23        B   62.0  Product3  942.0  North       942.000000
23  2023-01-24        C   92.0  Product2  342.0   West       342.000000
24  2023-01-25        A   24.0  Product2  458.0   East       458.000000
25  2023-01-26        C   95.0  Product1  584.0   West       584.000000
26  2023-01-27        C   71.0  Product2  619.0  North       619.000000
27  2023-01-28        C   56.0  Product2  224.0  North       224.000000
28  2023-01-29        B    NaN  Product3  617.0  North       617.000000
29  2023-01-30        C   51.0  Product2  737.0  South       737.000000
30  2023-01-31        B   50.0  Product3  735.0   West       735.000000
31  2023-02-01        A   17.0  Product2  189.0   West       189.000000
32  2023-02-02        B   63.0  Product3  338.0  South       338.000000
33  2023-02-03        C   27.0  Product3    NaN   East       557.130435
34  2023-02-04        C   70.0  Product3  669.0   West       669.000000
35  2023-02-05        B   60.0  Product2    NaN   West       557.130435
36  2023-02-06        C   36.0  Product3  177.0   East       177.000000
37  2023-02-07        C    2.0  Product1    NaN  North       557.130435
38  2023-02-08        C   94.0  Product1  408.0  South       408.000000
39  2023-02-09        A   62.0  Product1  155.0   West       155.000000
40  2023-02-10        B   15.0  Product1  578.0   East       578.000000
41  2023-02-11        C   97.0  Product1  256.0   East       256.000000
42  2023-02-12        A   93.0  Product3  164.0   West       164.000000
43  2023-02-13        A   43.0  Product3  949.0   East       949.000000
44  2023-02-14        A   96.0  Product3  830.0   East       830.000000
45  2023-02-15        B   99.0  Product2  599.0   West       599.000000
46  2023-02-16        B    6.0  Product1  938.0  South       938.000000
47  2023-02-17        B   69.0  Product3  143.0   West       143.000000
48  2023-02-18        C   65.0  Product3  182.0  North       182.000000
49  2023-02-19        C   11.0  Product3  708.0  North       708.000000

In [26]:
df['Sales_NA_int']=df['Sales'].fillna(df['Sales'].mean()).astype(int)
df

,date,category,Value,Product,Sales,Region,Sales_filled_NA,Sales_NA_int
0,2023-01-01,A,28.0,Product1,3016.000000,East,754.000000,3016
1,2023-01-02,B,39.0,Product3,440.000000,North,110.000000,440
2,2023-01-03,C,32.0,Product2,1592.000000,East,398.000000,1592
3,2023-01-04,B,8.0,Product1,2088.000000,East,522.000000,2088
4,2023-01-05,B,26.0,Product3,3476.000000,North,869.000000,3476
5,2023-01-06,B,54.0,Product3,768.000000,West,192.000000,768
6,2023-01-07,A,16.0,Product1,3744.000000,East,936.000000,3744
7,2023-01-08,C,89.0,Product1,1952.000000,West,488.000000,1952
8,2023-01-09,C,37.0,Product3,3088.000000,West,772.000000,3088
9,2023-01-10,A,22.0,Product2,3336.000000,West,834.000000,3336
10,2023-01-11,B,7.0,Product1,3368.000000,North,842.000000,3368
11,2023-01-12,B,60.0,Product2,2228.521739,West,557.130435,2228
12,2023-01-13,A,70.0,Product3,2512.000000,South,628.000000,2512
13,2023-01-14,A,69.0,Product1,1692.000000,East,423.000000,1692
14,2023-01-15,A,47.0,Product2,3572.000000,West,893.000000,3572
15,2023-01-16,C,NaN,Product1,3580.000000,North,895.000000,3580
16,2023-01-17,C,93.0,Product2,2044.000000,South,511.000000,2044
17,2023-01-18,C,NaN,Product1,432.000000,West,108.000000,432
18,2023-01-19,A,31.0,Product2,2312.000000,West,578.000000,2312
19,2023-01-20,A,59.0,Product1,2944.000000,East,736.000000,2944
20,2023-01-21,C,82.0,Product3,2424.000000,South,606.000000,2424
21,2023-01-22,C,37.0,Product2,3968.000000,South,992.000000,3968
22,2023-01-23,B,62.0,Product3,3768.000000,North,942.000000,3768
23,2023-01-24,C,92.0,Product2,1368.000000,West,342.000000,1368
24,2023-01-25,A,24.0,Product2,1832.000000,East,458.000000,1832
25,2023-01-26,C,95.0,Product1,2336.000000,West,584.000000,2336
26,2023-01-27,C,71.0,Product2,2476.000000,North,619.000000,2476
27,2023-01-28,C,56.0,Product2,896.000000,North,224.000000,896
28,2023-01-29,B,NaN,Product3,2468.000000,North,617.000000,2468
29,2023-01-30,C,51.0,Product2,2948.000000,South,737.000000,2948
30,2023-01-31,B,50.0,Product3,2940.000000,West,735.000000,2940
31,2023-02-01,A,17.0,Product2,756.000000,West,189.000000,756
32,2023-02-02,B,63.0,Product3,1352.000000,South,338.000000,1352
33,2023-02-03,C,27.0,Product3,2228.521739,East,557.130435,2228
34,2023-02-04,C,70.0,Product3,2676.000000,West,669.000000,2676
35,2023-02-05,B,60.0,Product2,2228.521739,West,557.130435,2228
36,2023-02-06,C,36.0,Product3,708.000000,East,177.000000,708
37,2023-02-07,C,2.0,Product1,2228.521739,North,557.130435,2228
38,2023-02-08,C,94.0,Product1,1632.000000,South,408.000000,1632
39,2023-02-09,A,62.0,Product1,620.000000,West,155.000000,620
40,2023-02-10,B,15.0,Product1,2312.000000,East,578.000000,2312
41,2023-02-11,C,97.0,Product1,1024.000000,East,256.000000,1024
42,2023-02-12,A,93.0,Product3,656.000000,West,164.000000,656
43,2023-02-13,A,43.0,Product3,3796.000000,East,949.000000,3796
44,2023-02-14,A,96.0,Product3,3320.000000,East,830.000000,3320
45,2023-02-15,B,99.0,Product2,2396.000000,West,599.000000,2396
46,2023-02-16,B,6.0,Product1,3752.000000,South,938.000000,3752
47,2023-02-17,B,69.0,Product3,572.000000,West,143.000000,572
48,2023-02-18,C,65.0,Product3,728.000000,North,182.000000,728
49,2023-02-19,C,11.0,Product3,2832.000000,North,708.000000,2832

In [28]:
df['Sales']=df['Sales'].apply(lambda x:x//2)
df

,date,category,Value,Product,Sales,Region,Sales_filled_NA,Sales_NA_int
0,2023-01-01,A,28.0,Product1,754.0,East,754.000000,3016
1,2023-01-02,B,39.0,Product3,110.0,North,110.000000,440
2,2023-01-03,C,32.0,Product2,398.0,East,398.000000,1592
3,2023-01-04,B,8.0,Product1,522.0,East,522.000000,2088
4,2023-01-05,B,26.0,Product3,869.0,North,869.000000,3476
5,2023-01-06,B,54.0,Product3,192.0,West,192.000000,768
6,2023-01-07,A,16.0,Product1,936.0,East,936.000000,3744
7,2023-01-08,C,89.0,Product1,488.0,West,488.000000,1952
8,2023-01-09,C,37.0,Product3,772.0,West,772.000000,3088
9,2023-01-10,A,22.0,Product2,834.0,West,834.000000,3336
10,2023-01-11,B,7.0,Product1,842.0,North,842.000000,3368
11,2023-01-12,B,60.0,Product2,557.0,West,557.130435,2228
12,2023-01-13,A,70.0,Product3,628.0,South,628.000000,2512
13,2023-01-14,A,69.0,Product1,423.0,East,423.000000,1692
14,2023-01-15,A,47.0,Product2,893.0,West,893.000000,3572
15,2023-01-16,C,NaN,Product1,895.0,North,895.000000,3580
16,2023-01-17,C,93.0,Product2,511.0,South,511.000000,2044
17,2023-01-18,C,NaN,Product1,108.0,West,108.000000,432
18,2023-01-19,A,31.0,Product2,578.0,West,578.000000,2312
19,2023-01-20,A,59.0,Product1,736.0,East,736.000000,2944
20,2023-01-21,C,82.0,Product3,606.0,South,606.000000,2424
21,2023-01-22,C,37.0,Product2,992.0,South,992.000000,3968
22,2023-01-23,B,62.0,Product3,942.0,North,942.000000,3768
23,2023-01-24,C,92.0,Product2,342.0,West,342.000000,1368
24,2023-01-25,A,24.0,Product2,458.0,East,458.000000,1832
25,2023-01-26,C,95.0,Product1,584.0,West,584.000000,2336
26,2023-01-27,C,71.0,Product2,619.0,North,619.000000,2476
27,2023-01-28,C,56.0,Product2,224.0,North,224.000000,896
28,2023-01-29,B,NaN,Product3,617.0,North,617.000000,2468
29,2023-01-30,C,51.0,Product2,737.0,South,737.000000,2948
30,2023-01-31,B,50.0,Product3,735.0,West,735.000000,2940
31,2023-02-01,A,17.0,Product2,189.0,West,189.000000,756
32,2023-02-02,B,63.0,Product3,338.0,South,338.000000,1352
33,2023-02-03,C,27.0,Product3,557.0,East,557.130435,2228
34,2023-02-04,C,70.0,Product3,669.0,West,669.000000,2676
35,2023-02-05,B,60.0,Product2,557.0,West,557.130435,2228
36,2023-02-06,C,36.0,Product3,177.0,East,177.000000,708
37,2023-02-07,C,2.0,Product1,557.0,North,557.130435,2228
38,2023-02-08,C,94.0,Product1,408.0,South,408.000000,1632
39,2023-02-09,A,62.0,Product1,155.0,West,155.000000,620
40,2023-02-10,B,15.0,Product1,578.0,East,578.000000,2312
41,2023-02-11,C,97.0,Product1,256.0,East,256.000000,1024
42,2023-02-12,A,93.0,Product3,164.0,West,164.000000,656
43,2023-02-13,A,43.0,Product3,949.0,East,949.000000,3796
44,2023-02-14,A,96.0,Product3,830.0,East,830.000000,3320
45,2023-02-15,B,99.0,Product2,599.0,West,599.000000,2396
46,2023-02-16,B,6.0,Product1,938.0,South,938.000000,3752
47,2023-02-17,B,69.0,Product3,143.0,West,143.000000,572
48,2023-02-18,C,65.0,Product3,182.0,North,182.000000,728
49,2023-02-19,C,11.0,Product3,708.0,North,708.000000,2832

In [29]:
df.head()

,date,category,Value,Product,Sales,Region,Sales_filled_NA,Sales_NA_int
0,2023-01-01,A,28.0,Product1,754.0,East,754.0,3016
1,2023-01-02,B,39.0,Product3,110.0,North,110.0,440
2,2023-01-03,C,32.0,Product2,398.0,East,398.0,1592
3,2023-01-04,B,8.0,Product1,522.0,East,522.0,2088
4,2023-01-05,B,26.0,Product3,869.0,North,869.0,3476

In [33]:
grouped1 = df.groupby('Product')['Value'].sum()
print(grouped1)

Product
Product1    647.0
Product2    792.0
Product3    993.0
Name: Value, dtype: float64

In [35]:
grouped2 = df.groupby(['Region', 'Product'])['Value'].sum()
print(grouped2)

Region  Product
East    Product1    292.0
        Product2     56.0
        Product3    202.0
North   Product1      9.0
        Product2    127.0
        Product3    203.0
South   Product1    100.0
        Product2    181.0
        Product3    215.0
West    Product1    246.0
        Product2    428.0
        Product3    373.0
Name: Value, dtype: float64

In [36]:
grouped2 = df.groupby(['Region', 'Product'])['Value'].agg(['mean','sum','count'])
print(grouped2)

                      mean    sum  count
Region Product
East   Product1  41.714286  292.0      7
       Product2  28.000000   56.0      2
       Product3  50.500000  202.0      4
North  Product1   4.500000    9.0      2
       Product2  63.500000  127.0      2
       Product3  40.600000  203.0      5
South  Product1  50.000000  100.0      2
       Product2  60.333333  181.0      3
       Product3  71.666667  215.0      3
West   Product1  82.000000  246.0      3
       Product2  53.500000  428.0      8
       Product3  62.166667  373.0      6

In [37]:
df1 = pd.DataFrame({'Key': ['A', 'B', 'C'], 'Value1': [1, 2, 3]})
df2 = pd.DataFrame({'Key': ['A', 'B', 'D'], 'Value2': [4, 5, 6]})

In [38]:
pd.merge(df1,df2,on='Key',how='inner')

  Key  Value1  Value2
0   A       1       4
1   B       2       5

In [40]:
pd.merge(df1,df2,on='Key',how='outer')

  Key  Value1  Value2
0   A     1.0     4.0
1   B     2.0     5.0
2   C     3.0     NaN
3   D     NaN     6.0

In [43]:
from io import StringIO

Data = '{"employee_name": "James", "email": "james@gmail.com", "job_profile": [{"title1":"Team Lead", "title2":"Sr. Developer"}]}'
df=pd.read_json(StringIO(Data))
df

,employee_name,email,job_profile
0,James,james@gmail.com,"{'title1': 'Team Lead', 'title2': 'Sr. Develop..."

In [44]:
df.to_json()

'{"employee_name":{"0":"James"},"email":{"0":"james@gmail.com"},"job_profile":{"0":{"title1":"Team Lead","title2":"Sr. Developer"}}}'

In [45]:
df.to_json(orient='records')

'[{"employee_name":"James","email":"james@gmail.com","job_profile":{"title1":"Team Lead","title2":"Sr. Developer"}}]'

In [46]:
df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data')
df

,1,14.23,1.71,2.43,15.6,127,2.8,3.06,.28,2.29,5.64,1.04,3.92,1065
0,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
1,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
2,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
3,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735
4,1,14.20,1.76,2.45,15.2,112,3.27,3.39,0.34,1.97,6.75,1.05,2.85,1450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
172,3,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740
173,3,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750
174,3,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835
175,3,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840
176,3,14.13,4.10,2.74,24.5,96,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560

In [47]:
df.head()

,1,14.23,1.71,2.43,15.6,127,2.8,3.06,.28,2.29,5.64,1.04,3.92,1065
0,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
1,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
2,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
3,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735
4,1,14.20,1.76,2.45,15.2,112,3.27,3.39,0.34,1.97,6.75,1.05,2.85,1450

In [49]:
# These 3 dependencies are required to read tables from any website html
!pip install lxml
!pip install html5lib
!pip install beautifulsoup4

Requirement already satisfied: lxml in .\plainPython\Lib\site-packages (6.0.2)
Requirement already satisfied: html5lib in .\plainPython\Lib\site-packages (1.1)
Requirement already satisfied: six>=1.9 in .\plainPython\Lib\site-packages (from html5lib) (1.17.0)
Requirement already satisfied: webencodings in .\plainPython\Lib\site-packages (from html5lib) (0.5.1)
Requirement already satisfied: beautifulsoup4 in .\plainPython\Lib\site-packages (4.14.3)
Requirement already satisfied: soupsieve>=1.6.1 in .\plainPython\Lib\site-packages (from beautifulsoup4) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in .\plainPython\Lib\site-packages (from beautifulsoup4) (4.15.0)

In [50]:
url="https://www.fdic.gov/resources/resolutions/bank-failures/failed-bank-list/"

df=pd.read_html(url)

In [51]:
df

[                                            Bank Name                City  \
 0                   Metropolitan Capital Bank & Trust             Chicago
 1                        The Santa Anna National Bank          Santa Anna
 2                                Pulaski Savings Bank             Chicago
 3                  The First National Bank of Lindsay             Lindsay
 4               Republic First Bank dba Republic Bank        Philadelphia
 5                                       Citizens Bank            Sac City
 6                            Heartland Tri-State Bank             Elkhart
 7                                 First Republic Bank       San Francisco
 8                                      Signature Bank            New York
 9                                 Silicon Valley Bank         Santa Clara
 10                                  Almena State Bank              Almena
 11                         First City Bank of Florida   Fort Walton Beach
 12                               The First State Bank       Barboursville
 13                                 Ericson State Bank             Ericson
 14                   City National Bank of New Jersey              Newark
 15                                      Resolute Bank              Maumee
 16                              Louisa Community Bank              Louisa
 17                               The Enloe State Bank              Cooper
 18                Washington Federal Bank for Savings             Chicago
 19    The Farmers and Merchants State Bank of Argonia             Argonia
 20                                Fayette County Bank          Saint Elmo
 21  Guaranty Bank, (d/b/a BestBank in Georgia & Mi...           Milwaukee
 22                                     First NBC Bank         New Orleans
 23                                      Proficio Bank  Cottonwood Heights
 24                      Seaway Bank and Trust Company             Chicago

             State   Cert                Acquiring Institution  \
 0        Illinois  57488              First Independence Bank
 1           Texas   5520            Coleman County State Bank
 2        Illinois  28611                      Millennium Bank
 3        Oklahoma   4134               First Bank & Trust Co.
 4    Pennsylvania  27332    Fulton Bank, National Association
 5            Iowa   8758            Iowa Trust & Savings Bank
 6          Kansas  25851               Dream First Bank, N.A.
 7      California  59017            JPMorgan Chase Bank, N.A.
 8        New York  57053                  Flagstar Bank, N.A.
 9      California  24735  First–Citizens Bank & Trust Company
 10         Kansas  15426                          Equity Bank
 11        Florida  16748            United Fidelity Bank, fsb
 12  West Virginia  14361                       MVB Bank, Inc.
 13       Nebraska  18265           Farmers and Merchants Bank
 14     New Jersey  21111                      Industrial Bank
 15           Ohio  58317                   Buckeye State Bank
 16       Kentucky  58112    Kentucky Farmers Bank Corporation
 17          Texas  10716                   Legend Bank, N. A.
 18       Illinois  30570                   Royal Savings Bank
 19         Kansas  17719                          Conway Bank
 20       Illinois   1802            United Fidelity Bank, fsb
 21      Wisconsin  30003  First-Citizens Bank & Trust Company
 22      Louisiana  58302                         Whitney Bank
 23           Utah  35495                    Cache Valley Bank
 24       Illinois  19328                  State Bank of Texas

          Closing Date  Fund  Sort ascending
 0    January 30, 2026                 10550
 1       June 27, 2025                 10549
 2    January 17, 2025                 10548
 3    October 18, 2024                 10547
 4      April 26, 2024                 10546
 5    November 3, 2023                 10545
 6       July 28, 2023                 10544
 7         May 1, 2023                 10543
 8      March 12, 2023                 10540
 9      March 10, 2023                 10539
 10   October 23, 2020                 10538
 11   October 16, 2020                 10537
 12      April 3, 2020                 10536
 13  February 14, 2020                 10535
 14   November 1, 2019                 10534
 15   October 25, 2019                 10533
 16   October 25, 2019                 10532
 17       May 31, 2019                 10531
 18  December 15, 2017                 10530
 19   October 13, 2017                 10529
 20       May 26, 2017                 10528
 21        May 5, 2017                 10527
 22     April 28, 2017                 10526
 23      March 3, 2017                 10525
 24   January 27, 2017                 10524  ]

In [55]:
!pip install lxml

Requirement already satisfied: lxml in .\plainPython\Lib\site-packages (6.0.2)

In [58]:
!pip install requests

Collecting requests
  Downloading requests-2.33.0-py3-none-any.whl.metadata (5.1 kB)
Collecting charset_normalizer<4,>=2 (from requests)
  Downloading charset_normalizer-3.4.6-cp312-cp312-win_amd64.whl.metadata (41 kB)
Collecting idna<4,>=2.5 (from requests)
  Using cached idna-3.11-py3-none-any.whl.metadata (8.4 kB)
Collecting urllib3<3,>=1.26 (from requests)
  Using cached urllib3-2.6.3-py3-none-any.whl.metadata (6.9 kB)
Collecting certifi>=2023.5.7 (from requests)
  Downloading certifi-2026.2.25-py3-none-any.whl.metadata (2.5 kB)
Downloading requests-2.33.0-py3-none-any.whl (65 kB)
Downloading charset_normalizer-3.4.6-cp312-cp312-win_amd64.whl (154 kB)
Using cached idna-3.11-py3-none-any.whl (71 kB)
Using cached urllib3-2.6.3-py3-none-any.whl (131 kB)
Downloading certifi-2026.2.25-py3-none-any.whl (153 kB)
Installing collected packages: urllib3, idna, charset_normalizer, certifi, requests

   ---------------------------------------- 0/5 [urllib3]
   ---------------------------------------- 0/5 [urllib3]
   ---------------------------------------- 0/5 [urllib3]
   -------- ------------------------------- 1/5 [idna]
   ---------------- ----------------------- 2/5 [charset_normalizer]
   ---------------- ----------------------- 2/5 [charset_normalizer]
   ---------------- ----------------------- 2/5 [charset_normalizer]
   -------------------------------- ------- 4/5 [requests]
   -------------------------------- ------- 4/5 [requests]
   ---------------------------------------- 5/5 [requests]

Successfully installed certifi-2026.2.25 charset_normalizer-3.4.6 idna-3.11 requests-2.33.0 urllib3-2.6.3

In [61]:
import pandas as pd
import requests
from io import StringIO

url = "https://en.wikipedia.org/wiki/Mobile_country_code"

headers = {
    "User-Agent": "Mozilla/5.0"
}

html = requests.get(url, headers=headers).text

df = pd.read_html(StringIO(html), match="Country", header=0)[0]

df.head()

,Mobile country code,Country,ISO 3166,Mobile network codes,National MNC authority,Remarks
0,289,A Abkhazia,GE-AB,List of mobile network codes in Abkhazia,NaN,MCC is not listed by ITU
1,412,Afghanistan,AF,List of mobile network codes in Afghanistan,NaN,NaN
2,276,Albania,AL,List of mobile network codes in Albania,NaN,NaN
3,603,Algeria,DZ,List of mobile network codes in Algeria,NaN,NaN
4,544,American Samoa (United States of America),AS,List of mobile network codes in American Samoa,NaN,NaN

In [65]:
# To read excel file
!pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

In [66]:
df_excel=pd.read_excel('data.xlsx')

In [67]:
df_excel

    Name  Age
0  Krish   32
1   Jack   34
2   John   31

In [69]:
df_excel.to_pickle('df_excel')

In [70]:
pd.read_pickle('df_excel')

    Name  Age
0  Krish   32
1   Jack   34
2   John   31

In [71]:
!pip install matplotlib

Collecting matplotlib
  Downloading matplotlib-3.10.8-cp312-cp312-win_amd64.whl.metadata (52 kB)
Collecting contourpy>=1.0.1 (from matplotlib)
  Downloading contourpy-1.3.3-cp312-cp312-win_amd64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib)
  Downloading cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib)
  Downloading fonttools-4.62.1-cp312-cp312-win_amd64.whl.metadata (119 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Downloading kiwisolver-1.5.0-cp312-cp312-win_amd64.whl.metadata (5.2 kB)
Requirement already satisfied: numpy>=1.23 in .\plainPython\Lib\site-packages (from matplotlib) (2.4.3)
Requirement already satisfied: packaging>=20.0 in .\plainPython\Lib\site-packages (from matplotlib) (25.0)
Collecting pillow>=8 (from matplotlib)
  Downloading pillow-12.1.1-cp312-cp312-win_amd64.whl.metadata (9.0 kB)
Collecting pyparsing>=3 (from matplotlib)
  Downloading pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: python-dateutil>=2.7 in .\plainPython\Lib\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in .\plainPython\Lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Downloading matplotlib-3.10.8-cp312-cp312-win_amd64.whl (8.1 MB)
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   ----------------------- ---------------- 4.7/8.1 MB 25.9 MB/s eta 0:00:01
   ---------------------------------------- 8.1/8.1 MB 22.9 MB/s  0:00:00
Downloading contourpy-1.3.3-cp312-cp312-win_amd64.whl (226 kB)
Downloading cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fonttools-4.62.1-cp312-cp312-win_amd64.whl (2.3 MB)
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ---------------------------------------- 2.3/2.3 MB 19.0 MB/s  0:00:00
Downloading kiwisolver-1.5.0-cp312-cp312-win_amd64.whl (73 kB)
Downloading pillow-12.1.1-cp312-cp312-win_amd64.whl (7.0 MB)
   ---------------------------------------- 0.0/7.0 MB ? eta -:--:--
   -------------------------- ------------- 4.7/7.0 MB 22.0 MB/s eta 0:00:01
   ---------------------------------------- 7.0/7.0 MB 21.6 MB/s  0:00:00
Downloading pyparsing-3.3.2-py3-none-any.whl (122 kB)
Installing collected packages: pyparsing, pillow, kiwisolver, fonttools, cycler, contourpy, matplotlib

   ---------------------------------------- 0/7 [pyparsing]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ---------------------------- ----------- 5/7 [contourpy]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------------- 7/7 [matplotlib]

Successfully installed contourpy-1.3.3 cycler-0.12.1 fonttools-4.62.1 kiwisolver-1.5.0 matplotlib-3.10.8 pillow-12.1.1 pyparsing-3.3.2